# Site settings
title: "Land Registry Digital Service"
description: "Land Registry Digital Service"
author: "Land Registry Digital Service"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]
