# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jago Home
tagline:          'The Jago House Swaps'
description:      'All about our house, the surrounding area and our house swaps'
url:              http://www.jagohome.co.uk
baseurl:          /

author:
  name:           'Spencer Jago'
  url:            https://twitter.com/spannerj

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/spencerjago/spencerjago.github.io
